# ====================================================================================== #
#
#  Workflow : 빌드 테스트 - Java Gradle
#
#  Workflow 설명 :
#    - Java Gradle Build를 통해 소스 코드 정상 빌드 여부 확인
#      : 개발 소스에 대한 빌드는 Dockerfile에서 multi-stage 빌드로 수행 필요
#         ** multi-stage 빌드 사용을 안할 경우 Workflow 내에 소스 빌드 단계를 수동으로 추가
#
#  버전 : v1.0
#
# ====================================================================================== #
name: Build Test

on:
  push:
    branches:
      - feature/**

env:
  JAVA_VERSION: 11 # JAVA REF: https://github.com/marketplace/actions/setup-java-jdk
  JAVA_DISTRIBUTION: temurin # JAVA REF 링크를 참고하여 필요 Java 버전 및 Distribution을 설정

jobs:
  build-test:
    name: TEST - Build
    runs-on: ubuntu-latest

    steps:
      - name: 소스 코드 Checkout
        uses: actions/checkout@v3

      # ========================================================================== #
      #    소스 코드 빌드 영역
      # ========================================================================== #
      - name: Java 환경 구성
        uses: actions/setup-java@v3
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: gradle

      - name: Gradlew 빌드 수행
        run: |
          chmod +x gradlew
          ./gradlew clean build

# ========================================================================== #
